EXEC sp_MSforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT all";
GO

DELETE FROM [dbo].[MenuRatings];
DELETE FROM [dbo].[Comments];
DELETE FROM [dbo].[RecipeRatings];
DELETE FROM [dbo].[MenuRecipes];
DELETE FROM [dbo].[RecipeSteps];
DELETE FROM [dbo].[CategoryRecipe];
DELETE FROM [dbo].[Menus];
DELETE FROM [dbo].[Recipes];
DELETE FROM [dbo].[Categories];
DELETE FROM [dbo].[Appeals];
DELETE FROM [dbo].[Users];
GO

DBCC CHECKIDENT ('[dbo].[MenuRatings]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Comments]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[RecipeRatings]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Menus]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[RecipeSteps]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Recipes]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Categories]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Appeals]', RESEED, 0);
DBCC CHECKIDENT ('[dbo].[Users]', RESEED, 0);
GO

SET IDENTITY_INSERT [dbo].[Users] ON;
GO

DECLARE @HashedPassword NVARCHAR(MAX) = '$2a$11$i9Pe/acWBiViOeY.TEo5FuyNWQvrGRa58P6uwSYjR8SeDalcKr8/S';

INSERT INTO [dbo].[Users] ([Id], [Name], [Surname], [Email], [Password], [Role], [IsActive]) VALUES
(1, 'Admin', 'User', 'admin@cookingsharp.com', @HashedPassword, 0, 1),
(2, 'Elena', 'Gomez', 'chef1@gmail.com', @HashedPassword, 1, 1),
(3, 'Carlos', 'Rodriguez', 'chef2@gmail.com', @HashedPassword, 1, 1),
(4, 'Ana', 'Martinez', 'chef3@gmail.com', @HashedPassword, 1, 1),
(5, 'Javier', 'Lopez', 'chef4@gmail.com', @HashedPassword, 1, 1),
(6, 'Sofia', 'Perez', 'chef5@gmail.com', @HashedPassword, 1, 1),
(27, 'Lucia', 'Fernandez', 'usuario1@gmail.com', @HashedPassword, 2, 1),
(28, 'David', 'Garcia', 'usuario2@gmail.com', @HashedPassword, 2, 1),
(29, 'Paula', 'Sanchez', 'usuario3@gmail.com', @HashedPassword, 2, 1),
(30, 'Daniel', 'Moreno', 'usuario4@gmail.com', @HashedPassword, 2, 1),
(31, 'Laura', 'Jimenez', 'usuario5@gmail.com', @HashedPassword, 2, 1);
GO

SET IDENTITY_INSERT [dbo].[Users] OFF;
GO

SET IDENTITY_INSERT [dbo].[Categories] ON;
GO

INSERT INTO [dbo].[Categories] ([Id], [Name], [Description]) VALUES
(1, 'Postres', 'Recetas dulces para después de la comida.'),
(2, 'Comida Italiana', 'Pastas, pizzas y más delicias de Italia.'),
(3, 'Cocina Asiática', 'Sabores de Japón, China, Tailandia y más.'),
(4, 'Ensaladas', 'Platos frescos y saludables.'),
(5, 'Sopas y Cremas', 'Platos reconfortantes.'),
(6, 'Carnes Rojas', 'Cortes de res, cerdo y cordero.'),
(7, 'Aves', 'Recetas con pollo, pavo y otras aves.'),
(8, 'Pescados y Mariscos', 'Delicias del mar.'),
(9, 'Vegetariano', 'Platos sin carne.'),
(10, 'Vegano', 'Recetas sin productos de origen animal.'),
(11, 'Panadería', 'Panes, masas y bollería.'),
(12, 'Bebidas y Cócteles', 'Batidos y cócteles.');
GO

SET IDENTITY_INSERT [dbo].[Categories] OFF;
GO

SET IDENTITY_INSERT [dbo].[Recipes] ON;
GO

DECLARE @DefaultImageURL NVARCHAR(MAX) = 'https://res.cloudinary.com/dg9woktw6/image/upload/v1761579215/eccmjyoctqubhws8pqyg.png';
DECLARE @DefaultImagePublicId NVARCHAR(MAX) = 'eccmjyoctqubhws8pqyg';

INSERT INTO [dbo].[Recipes] ([Id], [Name], [Description], [Status], [UserId], [ImageUrl], [ImagePublicId]) VALUES
(1, 'Tiramisú Clásico Italiano', 'Vainillas mojadas en café con crema de mascarpone.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(2, 'Lasaña de Carne a la Boloñesa', 'Pasta al horno con carne picada, tomate y bechamel.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(3, 'Pollo Teriyaki con Arroz', 'Pollo en salsa teriyaki con arroz blanco.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(4, 'Ensalada César con Pollo a la Parrilla', 'Lechuga con pollo, parmesano y salsa césar.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(5, 'Crema de Calabaza y Zanahoria', 'Sopa cremosa de verduras de temporada.', 0, 5, @DefaultImageURL, @DefaultImagePublicId),
(6, 'Solomillo de Cerdo en Salsa de Champiñones', 'Lomo de cerdo con salsa de hongos frescos.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(7, 'Paella Valenciana', 'Arroz con pollo, conejo y verduras estilo tradicional.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(8, 'Tacos de Pescado Estilo Baja', 'Pescado rebozado con repollo y salsa de chipotle.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(9, 'Risotto de Hongos', 'Arroz cremoso con mezcla de hongos frescos.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(10, 'Hamburguesa BBQ con Panceta', 'Hamburguesa de carne con salsa barbacoa, panceta y cheddar.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(11, 'Pad Thai de Langostinos', 'Fideos de arroz salteados con langostinos y maní.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(12, 'Chili con Carne', 'Guiso picante de carne molida con porotos rojos.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(13, 'Sushi Rolls Variados', 'Variedad de makis con salmón, atún y pepino.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(14, 'Pizza Margherita Napolitana', 'Pizza con tomate, mozzarella fresca y albahaca.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(15, 'Ramen de Cerdo', 'Sopa japonesa con fideos, cerdo chashu y huevo marinado.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(16, 'Fajitas de Pollo', 'Tiras de pollo con morrón y cebolla salteados.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(17, 'Gazpacho Andaluz', 'Sopa fría de tomate, morrón y pepino.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(18, 'Costillas BBQ al Horno', 'Costillas de cerdo con salsa barbacoa glaseadas.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(19, 'Tortilla de Papas', 'Tortilla de papas con cebolla estilo español.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(20, 'Ceviche de Pescado', 'Pescado marinado en limón con cebolla morada y cilantro.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(21, 'Curry Verde Tailandés', 'Curry con leche de coco, pollo y vegetales.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(22, 'Brownies de Chocolate', 'Bizcochuelo denso de chocolate con nueces.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(23, 'Enchiladas Verdes', 'Tortillas rellenas de pollo con salsa verde.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(24, 'Gnocchi con Salsa de Tomate', 'Ñoquis de papa con salsa de tomate casera.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(25, 'Pollo al Curry Indio', 'Pollo en salsa cremosa de curry con especias.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(26, 'Tarta de Queso New York', 'Cheesecake cremoso con base de galletitas.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(27, 'Empanadas Argentinas', 'Empanadas criollas rellenas de carne cortada a cuchillo.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(28, 'Ratatouille', 'Verduras mediterráneas al horno.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(29, 'Bacalao al Pil Pil', 'Bacalao confitado en aceite de oliva con ajos.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(30, 'Tacos al Pastor', 'Carne de cerdo marinada con ananá y cilantro.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(31, 'Gyozas de Cerdo', 'Empanaditas japonesas rellenas de cerdo y verduras.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(32, 'Arroz con Leche', 'Postre cremoso de arroz con canela y limón.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(33, 'Poke Bowl de Salmón', 'Bowl hawaiano con salmón, arroz y edamame.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(34, 'Albóndigas en Salsa', 'Albóndigas de carne en salsa de tomate casera.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(35, 'Panqueques Americanos', 'Panqueques esponjosos con almíbar de maple.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(36, 'Bibimbap Coreano', 'Bowl de arroz con verduras, carne y huevo frito.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(37, 'Crema Catalana', 'Postre de crema quemada con azúcar caramelizado.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(38, 'Salmón Teriyaki', 'Filete de salmón glaseado con salsa teriyaki.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(39, 'Quiche Lorraine', 'Tarta salada con panceta y queso gruyere.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(40, 'Burritos de Carne', 'Tortilla grande rellena de carne, arroz y porotos.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(41, 'Coulant de Chocolate', 'Bizcochuelo con centro líquido de chocolate.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(42, 'Moussaka Griega', 'Gratinado de berenjenas con carne y bechamel.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(43, 'Fish and Chips', 'Pescado rebozado con papas fritas.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(44, 'Hummus Casero', 'Puré de garbanzos con tahini y limón.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(45, 'Alitas Picantes', 'Alitas de pollo con salsa buffalo.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(46, 'Panna Cotta', 'Postre italiano de crema cocida con frutos rojos.', 1, 5, @DefaultImageURL, @DefaultImagePublicId),
(47, 'Falafel con Tzatziki', 'Croquetas de garbanzo con salsa de yogur.', 1, 2, @DefaultImageURL, @DefaultImagePublicId),
(48, 'Carbonara Romana', 'Pasta con huevo, guanciale y pecorino.', 1, 3, @DefaultImageURL, @DefaultImagePublicId),
(49, 'Salteado de Vegetales', 'Verduras salteadas al wok con salsa de soja.', 1, 4, @DefaultImageURL, @DefaultImagePublicId),
(50, 'Tarta de Manzana', 'Tarta con compota de manzana y canela.', 1, 5, @DefaultImageURL, @DefaultImagePublicId)
SET IDENTITY_INSERT [dbo].[Recipes] OFF;
GO

INSERT INTO [dbo].[RecipeSteps] ([RecipeId], [StepNumber], [Instruction]) VALUES
(1, 1, 'Separar las yemas de las claras. Batir las yemas con el azúcar.'),
(1, 2, 'Agregar el mascarpone y mezclar bien.'),
(1, 3, 'Montar las claras a punto nieve e incorporar.'),
(2, 1, 'Rehogar la cebolla, zanahoria y apio. Agregar la carne picada.'),
(2, 2, 'Preparar la bechamel y cocinar la pasta.'),
(2, 3, 'Armar capas de pasta, boloñesa y bechamel. Mandar al horno.'),
(3, 1, 'Cortar el pollo en cubos y preparar la salsa teriyaki.'),
(3, 2, 'Saltear el pollo y agregar la salsa hasta que espese.'),
(4, 1, 'Lavar y cortar la lechuga. Cocinar el pollo a la parrilla.'),
(4, 2, 'Preparar el aderezo césar mezclando mayonesa, ajo, anchoas y limón.'),
(4, 3, 'Armar la ensalada con lechuga, pollo en tiras, crutones y parmesano.'),
(5, 1, 'Pelar y cortar la calabaza y zanahoria en cubos.'),
(5, 2, 'Cocinar las verduras en caldo hasta que estén blandas.'),
(5, 3, 'Procesar todo hasta obtener una crema suave. Condimentar.'),
(6, 1, 'Sellar el solomillo en una sartén caliente.'),
(6, 2, 'Saltear los hongos con ajo y cebolla.'),
(6, 3, 'Agregar crema y cocinar hasta que espese. Servir sobre la carne.'),
(7, 1, 'Dorar el pollo y el conejo cortado en trozos.'),
(7, 2, 'Agregar las judías verdes y el garrofón.'),
(7, 3, 'Poner el arroz y el caldo. Cocinar 18 minutos.'),
(8, 1, 'Rebozar el pescado en harina y freír hasta dorar.'),
(8, 2, 'Preparar el repollo con vinagre y cilantro.'),
(8, 3, 'Armar los tacos con tortilla, pescado, repollo y salsa.'),
(9, 1, 'Saltear los hongos con ajo y perejil.'),
(9, 2, 'Tostar el arroz con cebolla y agregar caldo de a poco.'),
(9, 3, 'Incorporar los hongos, manteca y parmesano.'),
(10, 1, 'Hacer las hamburguesas con carne picada condimentada.'),
(10, 2, 'Cocinar a la plancha 4 minutos de cada lado.'),
(10, 3, 'Armar con panceta, cheddar, cebolla y salsa BBQ.'),
(11, 1, 'Remojar los fideos de arroz en agua caliente.'),
(11, 2, 'Saltear los langostinos con ajo. Agregar los fideos escurridos.'),
(11, 3, 'Incorporar salsa de pescado, tamarindo, maní y cebollita de verdeo.'),
(12, 1, 'Dorar la carne molida con cebolla y morrón.'),
(12, 2, 'Agregar tomate, porotos, comino, ají molido y cocinar a fuego lento.'),
(12, 3, 'Dejar cocinar por 30 minutos hasta que espese.'),
(13, 1, 'Cocinar el arroz para sushi y dejarlo enfriar con vinagre de arroz.'),
(13, 2, 'Colocar una lámina de nori sobre la esterilla de bambú.'),
(13, 3, 'Poner arroz, rellenar con pescado y verduras. Enrollar y cortar.'),
(14, 1, 'Estirar la masa de pizza en forma redonda.'),
(14, 2, 'Poner salsa de tomate y agregar mozzarella.'),
(14, 3, 'Meter al horno a 250°C hasta que la base esté crocante.'),
(15, 1, 'Cocinar el caldo de cerdo durante 6 horas con huesos y especias.'),
(15, 2, 'Marinar el cerdo chashu y asarlo hasta que esté tierno.'),
(15, 3, 'Cocinar los fideos, armar el bowl con caldo, fideos, cerdo y huevo.'),
(16, 1, 'Cortar el pollo en tiras y condimentar con comino y paprika.'),
(16, 2, 'Saltear el pollo con morrón y cebolla en tiras.'),
(16, 3, 'Servir con tortillas, palta, crema y limón.'),
(17, 1, 'Cortar el tomate, morrón, pepino, cebolla y ajo.'),
(17, 2, 'Procesar todo con aceite de oliva, vinagre y pan remojado.'),
(17, 3, 'Enfriar en la heladera por 2 horas antes de servir.'),
(18, 1, 'Hervir las costillas por 30 minutos para ablandarlas.'),
(18, 2, 'Pintar con salsa barbacoa y llevar al horno a 180°C.'),
(18, 3, 'Cocinar por 1 hora, pintando cada 20 minutos.'),
(19, 1, 'Freír las papas cortadas en rodajas.'),
(19, 2, 'Batir los huevos y mezclar con las papas.'),
(19, 3, 'Cuajar en la sartén dándola vuelta.'),
(20, 1, 'Cortar el pescado en cubos pequeños.'),
(20, 2, 'Marinar con jugo de limón por 15 minutos hasta que se cocine.'),
(20, 3, 'Agregar cebolla morada, cilantro, ají y servir frío.'),
(21, 1, 'Licuar pasta de curry verde con leche de coco.'),
(21, 2, 'Cocinar el pollo cortado en cubos en la salsa.'),
(21, 3, 'Agregar verduras y cocinar hasta que estén tiernas.'),
(22, 1, 'Derretir chocolate con manteca.'),
(22, 2, 'Batir huevos con azúcar y agregar la mezcla de chocolate.'),
(22, 3, 'Incorporar harina y nueces. Hornear 25 minutos.'),
(23, 1, 'Cocinar el pollo desmenuzado con cebolla y ajo.'),
(23, 2, 'Preparar salsa verde con tomatillos, cilantro y chiles.'),
(23, 3, 'Rellenar tortillas, enrollar, cubrir con salsa y gratinar.'),
(24, 1, 'Hervir papas, pisarlas y mezclar con harina y huevo.'),
(24, 2, 'Formar los ñoquis y marcar con tenedor.'),
(24, 3, 'Hervir hasta que floten. Servir con salsa de tomate.'),
(25, 1, 'Marinar el pollo con yogur y especias por 2 horas.'),
(25, 2, 'Dorar el pollo en una olla con manteca.'),
(25, 3, 'Agregar cebolla, tomate, curry y crema. Cocinar 30 minutos.'),
(26, 1, 'Procesar galletitas y mezclar con manteca derretida.'),
(26, 2, 'Batir queso crema con azúcar y huevos.'),
(26, 3, 'Volcar sobre la base y hornear a baño maría.'),
(27, 1, 'Preparar el relleno: rehogar cebolla, agregar carne cortada a cuchillo.'),
(27, 2, 'Condimentar con comino, pimentón y dejar enfriar.'),
(27, 3, 'Rellenar discos de masa, hacer repulgue y hornear o freír.'),
(28, 1, 'Cortar berenjena, zapallito, tomate y morrón en rodajas.'),
(28, 2, 'Acomodar en capas en una fuente con aceite de oliva.'),
(28, 3, 'Hornear a 180°C por 40 minutos con tomillo y romero.'),
(29, 1, 'Desalar el bacalao en agua fría por 24 horas cambiando el agua.'),
(29, 2, 'Confitar el bacalao en aceite de oliva a fuego bajo con ajos.'),
(29, 3, 'Mover la sartén para emulsionar y formar la salsa pil pil.'),
(30, 1, 'Marinar la carne de cerdo con achiote, chiles y especias.'),
(30, 2, 'Asar la carne en un trompo o sartén hasta que esté dorada.'),
(30, 3, 'Servir en tortillas con ananá asado, cebolla y cilantro.'),
(31, 1, 'Mezclar cerdo picado con repollo, jengibre y salsa de soja.'),
(31, 2, 'Colocar relleno en discos de masa y cerrar haciendo pliegues.'),
(31, 3, 'Cocinar al vapor o freír hasta que estén doradas.'),
(32, 1, 'Cocinar el arroz en leche con cáscara de limón y canela.'),
(32, 2, 'Revolver constantemente para que no se pegue.'),
(32, 3, 'Agregar azúcar al final y servir frío con canela arriba.'),
(33, 1, 'Cocinar arroz de sushi y dejarlo enfriar.'),
(33, 2, 'Cortar el salmón en cubos y marinar con salsa de soja.'),
(33, 3, 'Armar el bowl con arroz, salmón, edamame, palta y sésamo.'),
(34, 1, 'Mezclar carne picada con pan rallado, huevo y especias.'),
(34, 2, 'Formar albóndigas y dorarlas en una sartén.'),
(34, 3, 'Cocinar en salsa de tomate casera por 20 minutos.'),
(35, 1, 'Mezclar harina, azúcar, polvo de hornear y sal.'),
(35, 2, 'Agregar leche, huevo y manteca derretida.'),
(35, 3, 'Cocinar en sartén hasta que salgan burbujas.'),
(36, 1, 'Cocinar arroz y preparar verduras salteadas por separado.'),
(36, 2, 'Dorar carne molida con ajo y salsa de soja.'),
(36, 3, 'Armar el bowl con arroz, verduras, carne, huevo frito y gochujang.'),
(37, 1, 'Calentar leche con cáscara de limón y canela.'),
(37, 2, 'Batir yemas con azúcar y maicena. Agregar la leche caliente.'),
(37, 3, 'Cocinar hasta que espese, enfriar y quemar azúcar arriba.'),
(38, 1, 'Preparar salsa teriyaki con salsa de soja, mirin y azúcar.'),
(38, 2, 'Sellar el salmón en una sartén caliente.'),
(38, 3, 'Glasear con la salsa teriyaki hasta que esté caramelizado.'),
(39, 1, 'Estirar masa quebrada en un molde y pre-hornear.'),
(39, 2, 'Dorar panceta y distribuir sobre la masa.'),
(39, 3, 'Batir huevos con crema y queso. Volcar y hornear 30 minutos.'),
(40, 1, 'Cocinar carne molida con especias mexicanas.'),
(40, 2, 'Preparar arroz y porotos refritos.'),
(40, 3, 'Rellenar tortilla grande, enrollar y calentar en plancha.'),
(41, 1, 'Derretir chocolate con manteca.'),
(41, 2, 'Batir huevos con azúcar y agregar al chocolate.'),
(41, 3, 'Hornear 8 minutos a 200°C para que quede líquido adentro.'),
(42, 1, 'Cortar y freír las berenjenas en rodajas.'),
(42, 2, 'Preparar carne molida con cebolla, tomate y canela.'),
(42, 3, 'Armar capas de berenjena y carne, cubrir con bechamel y hornear.'),
(43, 1, 'Rebozar el pescado en harina y cerveza. Freír hasta dorar.'),
(43, 2, 'Cortar papas en bastones y freír hasta que estén crocantes.'),
(43, 3, 'Servir con vinagre de malta y salsa tártara.'),
(44, 1, 'Remojar garbanzos toda la noche y cocinarlos hasta que estén blandos.'),
(44, 2, 'Procesar garbanzos con tahini, ajo, limón y aceite de oliva.'),
(44, 3, 'Condimentar con comino y servir con aceite de oliva arriba.'),
(45, 1, 'Cortar las alas de pollo en trozos y condimentar.'),
(45, 2, 'Freír o hornear hasta que estén doradas y crocantes.'),
(45, 3, 'Mezclar con salsa buffalo caliente y servir con aderezo ranch.'),
(46, 1, 'Calentar crema con azúcar y vainilla sin que hierva.'),
(46, 2, 'Agregar gelatina hidratada y mezclar bien.'),
(46, 3, 'Volcar en moldes y enfriar 4 horas. Servir con frutos rojos.'),
(47, 1, 'Procesar garbanzos cocidos con cebolla, ajo y especias.'),
(47, 2, 'Formar bolitas y freír hasta que estén doradas.'),
(47, 3, 'Servir con salsa tzatziki de yogur, pepino y ajo.'),
(48, 1, 'Cocinar la pasta en agua con sal.'),
(48, 2, 'Saltear el guanciale hasta que esté crocante.'),
(48, 3, 'Mezclar huevos con pecorino y agregar a la pasta.'),
(49, 1, 'Cortar todas las verduras en tiras o cubos parejos.'),
(49, 2, 'Calentar el wok a fuego alto con aceite.'),
(49, 3, 'Saltear las verduras rapidísimo y agregar salsa de soja.'),
(50, 1, 'Pelar y cortar las manzanas en láminas.'),
(50, 2, 'Cocinar con azúcar y canela hasta que estén blanditas.'),
(50, 3, 'Poner sobre masa quebrada y hornear.');
GO

INSERT INTO [dbo].[CategoryRecipe] ([CategoriesId], [RecipesId]) VALUES
(1, 1), (2, 1),
(2, 2), (6, 2),
(3, 3), (7, 3),
(4, 4), (7, 4),
(5, 5), (9, 5),
(6, 6),
(2, 7), (7, 7),
(8, 8), (3, 8),
(2, 9), (9, 9),
(6, 10),
(3, 11), (8, 11),
(6, 12),
(3, 13), (8, 13),
(2, 14),
(3, 15), (5, 15),
(7, 16),
(5, 17), (9, 17),
(6, 18),
(7, 19),
(8, 20),
(3, 21), (7, 21),
(1, 22),
(7, 23),
(2, 24), (9, 24),
(7, 25), (3, 25),
(1, 26),
(6, 27),
(9, 28),
(8, 29),
(6, 30),
(3, 31),
(1, 32),
(8, 33), (4, 33),
(6, 34),
(1, 35),
(3, 36), (6, 36),
(1, 37),
(8, 38),
(11, 39),
(6, 40),
(1, 41),
(6, 42), (9, 42),
(8, 43),
(9, 44), (10, 44),
(7, 45),
(1, 46),
(9, 47), (10, 47),
(2, 48),
(9, 49), (10, 49),
(1, 50);
GO

SET IDENTITY_INSERT [dbo].[Menus] ON;
GO

INSERT INTO [dbo].[Menus] ([Id], [Name], [Description], [UserId]) VALUES
(1, 'Cena Romántica Italiana', 'Menú completo con sabores de Italia.', 2),
(2, 'Menú Semanal Saludable', 'Platos equilibrados para la semana.', 4),
(3, 'Fiesta Mexicana', 'Sabores picantes y auténticos.', 3),
(4, 'Tour Asiático', 'Recetas de Japón, Tailandia y China.', 5),
(5, 'Brunch Domingo', 'Para comenzar bien el día.', 2);
GO

SET IDENTITY_INSERT [dbo].[Menus] OFF;
GO

INSERT INTO [dbo].[MenuRecipes] ([MenusId], [RecipesId]) VALUES
(1, 2), (1, 1),
(2, 4), (2, 6),
(3, 8), (3, 23), (3, 30),
(4, 13), (4, 15), (4, 21),
(5, 35), (5, 39);
GO

INSERT INTO [dbo].[RecipeRatings] ([RecipeId], [UserId], [Stars]) VALUES
(1, 27, 5), (1, 28, 4), (1, 29, 5), (1, 30, 5),
(2, 27, 5), (2, 30, 4), (2, 31, 5),
(3, 28, 4), (3, 31, 5), (3, 27, 4),
(4, 29, 4), (4, 30, 3), (4, 31, 5),
(7, 27, 5), (7, 28, 5), (7, 29, 4),
(8, 30, 4), (8, 31, 5),
(9, 27, 4), (9, 28, 5),
(10, 29, 5), (10, 30, 4), (10, 31, 5),
(11, 27, 5), (11, 28, 4),
(13, 29, 5), (13, 30, 5), (13, 31, 4),
(14, 27, 5), (14, 28, 5), (14, 29, 5), (14, 30, 4), (14, 31, 5),
(15, 31, 5), (15, 27, 4),
(19, 28, 5), (19, 29, 5), (19, 30, 5),
(20, 31, 4), (20, 27, 5),
(22, 28, 5), (22, 29, 5), (22, 30, 4), (22, 31, 5), (22, 27, 5),
(26, 27, 5), (26, 28, 4), (26, 29, 5),
(27, 27, 5), (27, 28, 5), (27, 29, 5), (27, 30, 4), (27, 31, 5),
(29, 30, 5), (29, 31, 4),
(33, 27, 4), (33, 28, 5),
(34, 27, 5), (34, 28, 4), (34, 29, 5), (34, 30, 5), (34, 31, 4),
(35, 29, 5), (35, 30, 5), (35, 31, 4),
(38, 27, 5), (38, 28, 5),
(41, 29, 5), (41, 30, 5), (41, 31, 5), (41, 27, 5), (41, 28, 4),
(43, 27, 4), (43, 28, 3),
(44, 29, 5), (44, 30, 4),
(45, 31, 5), (45, 27, 4),
(48, 28, 5), (48, 29, 5), (48, 30, 4), (48, 27, 5), (48, 31, 5),
(50, 31, 5), (50, 27, 4), (50, 28, 5);
GO

INSERT INTO [dbo].[Comments] ([RecipeId], [UserId], [Text], [CreatedAt]) VALUES
(1, 27, 'Me salió re bien, gracias por la receta!', GETUTCDATE()),
(1, 28, 'La hice para mi cumple y todos repitieron', GETUTCDATE()),
(2, 30, 'Le mandé un toque más de bechamel', GETUTCDATE()),
(2, 27, 'Me llevó 2 horas pero re vale la pena', GETUTCDATE()),
(3, 29, 'Muy rica, le tiré brócoli también', GETUTCDATE()),
(3, 31, 'No consigo mirin, con qué lo reemplazo?', GETUTCDATE()),
(4, 28, 'Re fácil y rápida, ideal para el verano', GETUTCDATE()),
(7, 27, 'Auténtica paella, me hace acordar a Valencia', GETUTCDATE()),
(7, 30, 'Le falta azafrán no?', GETUTCDATE()),
(8, 29, 'Los hice con pescadilla y quedaron tremendo', GETUTCDATE()),
(9, 31, 'Le puse champiñones, shiitake y portobello', GETUTCDATE()),
(10, 27, 'La carne quedó en su punto justo', GETUTCDATE()),
(10, 28, 'Mejor que en cualquier hamburguesería', GETUTCDATE()),
(11, 30, 'Primera vez haciendo pad thai, un golazo', GETUTCDATE()),
(13, 29, 'Los makis me salieron medio desprolijos pero riquísimos jajaja', GETUTCDATE()),
(13, 31, 'Cuánto arroz calculan por persona?', GETUTCDATE()),
(14, 27, 'La masa dejala reposar mínimo 2 horas', GETUTCDATE()),
(14, 28, 'Quedó re crocante como en Italia', GETUTCDATE()),
(14, 30, 'Le puse albahaca fresca de mi huerta', GETUTCDATE()),
(14, 29, 'Esta receta es la que más me gusta de todas', GETUTCDATE()),
(14, 31, 'Ya la hice como 10 veces, siempre sale perfecta', GETUTCDATE()),
(14, 27, 'La mejor pizza que hice en casa, no miento', GETUTCDATE()),
(15, 29, 'El huevo marinado es lo más del ramen', GETUTCDATE()),
(15, 27, 'Estuve todo el día haciendo el caldo pero la rompe', GETUTCDATE()),
(19, 28, 'Clásico español, me encanta', GETUTCDATE()),
(19, 31, 'Me costó darla vuelta pero al final zafó', GETUTCDATE()),
(20, 30, 'Usé corvina y quedó de 10', GETUTCDATE()),
(22, 27, 'No los dejen mucho tiempo que se secan, con 20 minutos va', GETUTCDATE()),
(22, 28, 'Les mandé chips de chocolate extra', GETUTCDATE()),
(22, 29, 'Me los comí todos yo sola en 2 días jajaja', GETUTCDATE()),
(22, 30, 'Estos brownies son adictivos mal', GETUTCDATE()),
(22, 31, 'Los llevé a una reunión y me pidieron la receta todos', GETUTCDATE()),
(22, 27, 'Ya van como 15 veces que los hago, nunca fallan', GETUTCDATE()),
(22, 28, 'Con helado de vainilla arriba son la gloria', GETUTCDATE()),
(26, 31, 'El mejor cheesecake que probé en mi vida', GETUTCDATE()),
(26, 27, 'Hay que hornear a baño maría sí o sí', GETUTCDATE()),
(27, 27, 'Las empanadas argentinas son las mejores del mundo', GETUTCDATE()),
(27, 28, 'La carne tiene que estar bien condimentada', GETUTCDATE()),
(27, 29, 'Las hice al horno y fritas, las dos formas son una delicia', GETUTCDATE()),
(27, 30, 'Puse huevo duro y aceitunas también', GETUTCDATE()),
(27, 31, 'La mejor receta de empanadas que encontré', GETUTCDATE()),
(27, 27, 'Mi familia las devora apenas salen del horno', GETUTCDATE()),
(27, 28, 'El repulgue me sale medio feo pero el sabor compensa jajaja', GETUTCDATE()),
(29, 30, 'Medio complicado de hacer pero un manjar', GETUTCDATE()),
(33, 28, 'Versión re saludable y muy rica', GETUTCDATE()),
(33, 29, 'Le puse palta y quedó mortal', GETUTCDATE()),
(34, 27, 'Las albóndigas me recuerdan a mi infancia', GETUTCDATE()),
(34, 28, 'Las hago grandes para que queden más jugosas', GETUTCDATE()),
(34, 29, 'Con puré de papas al lado son lo más', GETUTCDATE()),
(34, 30, 'La salsa tiene que tener un toque de ajo', GETUTCDATE()),
(34, 31, 'Hago el doble de cantidad y congelo para la semana', GETUTCDATE()),
(34, 27, 'Mis hijos las aman, es uno de sus platos favoritos', GETUTCDATE()),
(35, 27, 'Los hago todos los domingos', GETUTCDATE()),
(35, 31, 'Con manteca de maní son otra cosa', GETUTCDATE()),
(38, 28, 'El salmón tiene que estar re fresco', GETUTCDATE()),
(38, 30, 'Lo hice al horno y salió perfecto', GETUTCDATE()),
(41, 29, 'Tiene que quedar líquido adentro', GETUTCDATE()),
(41, 27, 'Ojo con el tiempo de horno, se pasa al toque', GETUTCDATE()),
(41, 30, 'Este postre es impresionante para las visitas', GETUTCDATE()),
(41, 31, 'Lo hice en una cena romántica y fue un éxito', GETUTCDATE()),
(41, 28, 'El chocolate tiene que ser de buena calidad', GETUTCDATE()),
(41, 29, 'Ya lo hice como 5 veces y siempre queda perfecto', GETUTCDATE()),
(43, 31, 'Típico inglés, con birra va de 10', GETUTCDATE()),
(44, 30, 'Lo uso para todo, hasta en ensaladas', GETUTCDATE()),
(45, 27, 'Re picantes, mejor ponerle menos salsa', GETUTCDATE()),
(45, 28, 'Las hice para ver el partido, re éxito', GETUTCDATE()),
(48, 29, 'La auténtica carbonara no lleva crema che!!', GETUTCDATE()),
(48, 30, 'Es medio jodido que no se corte el huevo pero voy a intentar de vuelta', GETUTCDATE()),
(48, 27, 'Esta es la receta que me enseñó mi nonna', GETUTCDATE()),
(48, 31, 'El pecorino es caro pero hace la diferencia', GETUTCDATE()),
(48, 28, 'La hago seguido, ya le agarré la mano', GETUTCDATE()),
(48, 29, 'Con mucha pimienta negra recién molida es otro nivel', GETUTCDATE()),
(50, 31, 'La tarta de la abuela, me pone re nostálgico', GETUTCDATE()),
(50, 28, 'Le puse manzanas verdes', GETUTCDATE()),
(1, 30, 'Cuánto tiempo aguanta en la heladera?', GETUTCDATE()),
(2, 29, 'Anda con carne de pavo?', GETUTCDATE()),
(7, 31, 'No tengo paellera, va con una sartén grande?', GETUTCDATE()),
(10, 29, 'Le puse cebolla caramelizada también', GETUTCDATE()),
(14, 31, 'A cuántos grados tiene que estar el horno?', GETUTCDATE()),
(14, 28, 'Che, alguien probó hacerla con harina integral?', GETUTCDATE()),
(19, 27, 'La hago con o sin cebolla según el día', GETUTCDATE()),
(22, 31, 'Probé con nueces pecanas y quedaron mejores', GETUTCDATE()),
(22, 29, 'Tip: poner un bowl de agua en el horno para que no se sequen', GETUTCDATE()),
(26, 30, 'Cuántas horas en la heladera necesita?', GETUTCDATE()),
(27, 29, 'Yo les pongo pasas de uva también', GETUTCDATE()),
(27, 30, 'El secreto está en la grasa de pella', GETUTCDATE()),
(34, 28, 'Van genial con fideos también', GETUTCDATE()),
(35, 30, 'Con banana y crema de cacahuate son adictivos', GETUTCDATE()),
(41, 31, 'Servilo con helado de vainilla, una bomba', GETUTCDATE()),
(41, 27, 'Tiene que estar calentito para que el centro chorree', GETUTCDATE()),
(48, 31, 'El guanciale es caríssimo, yo uso panceta', GETUTCDATE()),
(48, 27, 'La clave es mezclar rápido fuera del fuego', GETUTCDATE()),
(1, 29, 'Alguien sabe si se puede freezar?', GETUTCDATE()),
(2, 31, 'La próxima le mando más queso rallado arriba', GETUTCDATE()),
(3, 27, 'Che, queda bien con arroz yamani?', GETUTCDATE()),
(4, 30, 'Le puse crutones caseros y fue otro nivel', GETUTCDATE()),
(7, 28, 'Mi vieja la hace sin conejo, solo pollo', GETUTCDATE()),
(8, 27, 'La salsa picante es clave, no se la salteen', GETUTCDATE()),
(9, 30, 'Estuve media hora revolviendo pero valió la pena', GETUTCDATE()),
(10, 31, 'La hago en la parrilla y sale mucho mejor', GETUTCDATE()),
(11, 29, 'No encontré salsa de pescado, con qué lo sustituyo?', GETUTCDATE()),
(13, 27, 'Protip: mojen el cuchillo antes de cortar', GETUTCDATE()),
(14, 29, 'Probé con muzza de búfala y es otro planeta', GETUTCDATE()),
(14, 30, 'Hago dos pizzas al mismo tiempo para que alcance', GETUTCDATE()),
(15, 31, 'El caldo de cerdo lleva como 6 horas mínimo', GETUTCDATE()),
(19, 30, 'La clave es usar buenas papas y aceite de oliva', GETUTCDATE()),
(20, 29, 'Le pongo ají molido y le da un toque copado', GETUTCDATE()),
(22, 30, 'Tip: agregar un toque de café al chocolate', GETUTCDATE()),
(22, 27, 'Los dejo enfriar completamente antes de cortar', GETUTCDATE()),
(26, 28, 'Yo le pongo ralladura de limón a la mezcla', GETUTCDATE()),
(27, 31, 'Mi secreto: un chorrito de vino blanco en el relleno', GETUTCDATE()),
(27, 27, 'Las congelo crudas y las horneo cuando tengo gente', GETUTCDATE()),
(33, 31, 'Con salsa de soja y sésamo va re bien', GETUTCDATE()),
(34, 29, 'A veces les pongo un poco de pan rallado en la mezcla', GETUTCDATE()),
(34, 30, 'Con arroz blanco también quedan de 10', GETUTCDATE()),
(35, 29, 'Los hago con buttermilk casero y salen esponjosos', GETUTCDATE()),
(38, 27, 'Cuidado de no cocinar de más el salmón', GETUTCDATE()),
(41, 30, 'Es re importante que los moldes estén bien enmantecados', GETUTCDATE()),
(41, 28, 'Lo acompaño con frutas frescas y crema', GETUTCDATE()),
(44, 29, 'Le puse comino extra y quedó buenísimo', GETUTCDATE()),
(45, 31, 'Las hago al horno y quedan más sanas', GETUTCDATE()),
(48, 27, 'El truco es sacar la pasta del fuego antes de poner el huevo', GETUTCDATE()),
(48, 30, 'Uso solo yemas para que quede más cremosa', GETUTCDATE()),
(50, 29, 'Le pongo pasas de uva remojadas en ron jajaja', GETUTCDATE());
GO

INSERT INTO [dbo].[MenuRatings] ([MenuId], [UserId], [Stars]) VALUES
(1, 28, 5),
(1, 29, 4),
(1, 31, 5),
(2, 30, 5),
(2, 27, 4),
(3, 28, 5),
(3, 31, 5),
(4, 29, 4),
(4, 30, 5),
(5, 27, 5),
(5, 28, 4);
GO

EXEC sp_MSforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT all";
GO

PRINT 'Base de datos sembrada con éxito!';
GO